"""Personality-aware instruction engine for APEX teachers.

Generates tailored lesson content based on teacher profiles and learner state.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from apex.teachers.teacher_config import TeacherProfile, get_teacher


@dataclass
class LearnerState:
    """Snapshot of a learner's current state during instruction.

    Attributes:
        current_topic: The topic currently being studied.
        errors: Recent mistakes the learner has made.
        attempts: Number of attempts made on the current problem.
        confidence: Self-assessed confidence level from 0.0 (no confidence) to 1.0 (fully confident).
        pace: Preferred learning speed ('fast', 'normal', 'slow').
        preferred_teacher: Name of the learner's preferred teacher, or None.
    """

    current_topic: str = ""
    errors: list[str] = field(default_factory=list)
    attempts: int = 0
    confidence: float = 0.5
    pace: str = "normal"
    preferred_teacher: str | None = None


@dataclass
class LessonContent:
    """Complete lesson content generated by a teacher.

    Attributes:
        teacher_name: Name of the teacher who generated this content.
        topic: The lesson topic.
        greeting: Opening message from the teacher.
        explanation: Core explanatory content.
        example: Concrete example illustrating the concept.
        questions: Socratic or guiding questions to prompt learner thinking.
        practice_exercises: Exercises for the learner to practice.
        encouragement: Motivational closing message.
        tts_voice: TTS voice identifier for speech synthesis.
    """

    teacher_name: str
    topic: str
    greeting: str
    explanation: str
    example: str
    questions: list[str]
    practice_exercises: list[str]
    encouragement: str
    tts_voice: str


# ── Topic knowledge base ─────────────────────────────────────────────────────

# Simple topic descriptions used to generate personality-appropriate content.
# In a full system this would come from a knowledge graph or LLM.
_TOPIC_SUMMARY: dict[str, str] = {
    "variables": "A variable is a named container that stores a value in memory. You can think of it as a labeled box where you keep data that your program can use and modify.",
    "functions": "A function is a reusable block of code that performs a specific task. It takes inputs (parameters), does something with them, and returns an output.",
    "loops": "A loop is a control structure that repeats a block of code multiple times. It lets you automate repetitive tasks without writing the same code over and over.",
    "conditionals": "Conditionals let your program make decisions. They execute different code paths depending on whether a condition is true or false.",
    "classes": "A class is a blueprint for creating objects. It defines what data an object holds and what behaviors it can perform.",
    "arrays": "An array is a collection that stores multiple values of the same type in a contiguous block of memory, accessible by index.",
    "recursion": "Recursion is when a function calls itself to solve a smaller version of the same problem, until it reaches a base case that stops the cycle.",
    "sorting": "Sorting is the process of arranging elements in a specific order—usually ascending or descending—using algorithms like bubble sort, merge sort, or quicksort.",
}


def _get_topic_summary(topic: str) -> str:
    """Return a summary for the topic, or a generic fallback."""
    return _TOPIC_SUMMARY.get(
        topic.lower(),
        f"{topic} is a fundamental concept in computer science that forms the building block for more advanced topics.",
    )


# ── Teacher voice generators ─────────────────────────────────────────────────


def _generate_mentor_content(
    teacher: TeacherProfile, topic: str, state: LearnerState | None
) -> dict[str, Any]:
    """Generate content in The Mentor's Socratic, patient voice."""
    summary = _get_topic_summary(topic)
    explanation = (
        f"Let's explore {topic} together. {summary}\n\n"
        f"I'd like you to think about this: what happens when we use a variable "
        f"before giving it a value? Take a moment to reason through it."
    )
    example = (
        "Imagine you have a box labeled 'age'. You can put the number 25 in it, "
        "then later change it to 26. The box (variable) stays the same, but what's "
        "inside can change. That's the essence of a variable."
    )
    questions = [
        "What do you think would happen if we tried to use a variable that was never created?",
        "How would you explain a variable to someone who has never programmed before?",
        "Can you think of a real-world analogy for storing and retrieving data?",
    ]
    exercises = [
        "Create a variable called 'score' and set it to 0, then increment it by 10.",
        "Write a short paragraph explaining what a variable is in your own words.",
        "Predict what this code outputs: x = 5; y = x; x = 10; print(y)",
    ]
    encouragement = (
        "You're asking great questions—that's exactly how deep understanding grows. "
        "Keep exploring, and don't rush to conclusions. The journey matters as much as the answer."
    )
    return {
        "explanation": explanation,
        "example": example,
        "questions": questions,
        "practice_exercises": exercises,
        "encouragement": encouragement,
    }


def _generate_drill_sergeant_content(
    teacher: TeacherProfile, topic: str, state: LearnerState | None
) -> dict[str, Any]:
    """Generate content in The Drill Sergeant's direct, no-nonsense voice."""
    summary = _get_topic_summary(topic)
    explanation = (
        f"{topic.capitalize()}. {summary}\n\n"
        f"Here's what you need to know: a variable is declared with a name and "
        f"assigned a value. That's it. No magic. Now let's drill it."
    )
    example = (
        "Example: int count = 0; count = count + 1; // count is now 1. "
        "Simple. Do it again until you can't get it wrong."
    )
    questions = [
        "What is the syntax for declaring a variable? Answer now.",
        "What happens if you use a variable without initializing it? Don't guess—tell me.",
        "Write down three valid variable names and three invalid ones. Go.",
    ]
    exercises = [
        "Declare three variables of different types and assign them values. Now.",
        "Write a program that swaps the values of two variables. Do it without looking at notes.",
        "Identify the error in this code: x == 5; (fix it and explain why it was wrong).",
    ]
    encouragement = (
        "Good work—if you did it right. Mistakes mean you need more practice, not that "
        "you're incapable. Drill it again. Excellence is a habit, not an accident."
    )
    return {
        "explanation": explanation,
        "example": example,
        "questions": questions,
        "practice_exercises": exercises,
        "encouragement": encouragement,
    }


def _generate_guide_content(
    teacher: TeacherProfile, topic: str, state: LearnerState | None
) -> dict[str, Any]:
    """Generate content in The Guide's inquiry-based, resource-oriented voice."""
    summary = _get_topic_summary(topic)
    explanation = (
        f"Great, we're looking at {topic}. {summary}\n\n"
        f"Here's a question to orient us: what do you already know about this topic? "
        f"And what's still unclear? There's no rush—we'll find the resources that help."
    )
    example = (
        "Let's say you want to track a user's score in a game. You'd create a variable "
        "called 'score' and update it as the game progresses. The variable is your tool "
        "for remembering state. Want to see how this connects to other concepts? I can point you to resources on memory management and scope."
    )
    questions = [
        "What resources have you found helpful when learning similar topics?",
        "Where do you feel the most uncertainty about this concept?",
        "If you were to explain this to a peer, which part would you find hardest to describe?",
    ]
    exercises = [
        "Explore the official documentation for variables in your language of choice. Note three things you learned.",
        "Find a real-world code example that uses variables in an interesting way and explain what it does.",
        "Map out how variables relate to the concept of 'state' in programming. Draw a diagram if it helps.",
    ]
    encouragement = (
        "You're on the right track. Learning is about finding your own path through the material. "
        "I'm here to point you toward resources and help you ask better questions. What would you like to explore next?"
    )
    return {
        "explanation": explanation,
        "example": example,
        "questions": questions,
        "practice_exercises": exercises,
        "encouragement": encouragement,
    }


def _generate_storyteller_content(
    teacher: TeacherProfile, topic: str, state: LearnerState | None
) -> dict[str, Any]:
    """Generate content in The Storyteller's narrative, analogy-rich voice."""
    summary = _get_topic_summary(topic)
    explanation = (
        f"Ah, {topic}! Let me take you back to a time when programmers had to punch cards "
        f"by hand—each hole a memory cell, each card a variable. {summary}\n\n"
        f"The story of variables begins with Ada Lovelace, who imagined a machine that could "
        f"manipulate symbols, not just numbers. She called them 'variables' because they could "
        f"vary—change as the computation unfolded. That idea echoes through every program you write today."
    )
    example = (
        "Picture a medieval scribe maintaining a ledger. Each line has a label—'gold coins,' "
        "'silver rings,' 'land acres'—and a value that changes as trades happen. The labels are "
        "your variable names; the values are what's stored. The scribe doesn't rewrite the label, "
        "just updates the number. That's a variable in action, a story as old as record-keeping itself."
    )
    questions = [
        "What other stories from history remind you of how we store and change data today?",
        "If variables were characters in a novel, what kind of personalities would they have?",
        "How might the concept of a variable appear in a story about a journey or transformation?",
    ]
    exercises = [
        "Write a short story (2-3 paragraphs) where a variable is a character that changes throughout the plot.",
        "Find an analogy from nature, mythology, or daily life that captures what a variable does.",
        "Explain variables to a friend using only a story—no code, no technical terms.",
    ]
    encouragement = (
        f"Every great concept has a story, and you're now part of that story. "
        f"The beauty of {topic} isn't just in how it works—it's in why it mattered to those "
        f"who came before us, and how it will shape what comes next. Keep wondering."
    )
    return {
        "explanation": explanation,
        "example": example,
        "questions": questions,
        "practice_exercises": exercises,
        "encouragement": encouragement,
    }


# ── Content generation dispatch ──────────────────────────────────────────────

_STYLE_DISPATCH: dict[str, Callable[[TeacherProfile, str, LearnerState | None], dict[str, Any]]] = {
    "socratic": _generate_mentor_content,
    "direct": _generate_drill_sergeant_content,
    "inquiry": _generate_guide_content,
    "narrative": _generate_storyteller_content,
}


def _generate_content(
    teacher: TeacherProfile, topic: str, state: LearnerState | None
) -> dict[str, Any]:
    """Dispatch to the appropriate content generator based on teaching style."""
    generator = _STYLE_DISPATCH.get(teacher.teaching_style, _generate_mentor_content)
    return generator(teacher, topic, state)


# ── Socratic question generation ─────────────────────────────────────────────

_FOUNDATION_QUESTIONS: dict[str, list[str]] = {
    "variables": [
        "What problem does a variable solve that we couldn't solve before?",
        "If a variable is a box, what's on the outside of the box versus inside?",
        "When does a variable's value change, and when does it stay the same?",
        "What happens to a variable's value when the program ends?",
        "How would you explain the difference between a variable and a constant?",
    ],
    "functions": [
        "What makes a function different from just writing the code inline?",
        "Why do we pass parameters to a function instead of using global variables?",
        "What does it mean for a function to have a 'single responsibility'?",
        "When would you choose to write a function versus repeating code?",
        "How does a function's return value connect to the rest of the program?",
    ],
    "loops": [
        "What would happen if a loop never stopped? How do we prevent that?",
        "When is a for loop better than a while loop, and vice versa?",
        "What's the relationship between the loop body and the loop condition?",
        "How do you know when a loop has finished its job?",
        "Can you think of a situation where looping is the wrong approach?",
    ],
    "conditionals": [
        "What's the difference between an if statement and a loop?",
        "When would you use else-if instead of a separate if?",
        "What happens when none of the conditions in a chain are true?",
        "How do nested conditionals affect code readability?",
        "What's a real-world decision that works like a conditional?",
    ],
}


def generate_socratic_questions(teacher: TeacherProfile, topic: str, count: int = 3) -> list[str]:
    """Generate Socratic questions appropriate to the teacher's style.

    Args:
        teacher: The teacher profile whose style guides question generation.
        topic: The topic the questions should explore.
        count: Number of questions to generate (default 3).

    Returns:
        A list of Socratic questions tailored to the teacher and topic.
    """
    topic_key = topic.lower()
    pool = _FOUNDATION_QUESTIONS.get(
        topic_key,
        [
            f"What do you think {topic} is really about at its core?",
            f"How does {topic} connect to what you already know?",
            f"What would change if {topic} worked differently?",
            f"Why does {topic} matter in the bigger picture?",
            f"What question about {topic} still feels unanswered to you?",
        ],
    )

    # Different teachers ask questions differently
    if teacher.teaching_style == "socratic":
        # Mentor: open-ended, reflective, builds from learner's thinking
        selected = pool[:count]
        return [f"Reflect on this: {q}" for q in selected]

    if teacher.teaching_style == "direct":
        # Drill Sergeant: direct, challenging, demands answers
        selected = pool[:count]
        return [f"Answer directly: {q}" for q in selected]

    if teacher.teaching_style == "inquiry":
        # Guide: leading, exploratory, connects to resources
        selected = pool[:count]
        return [f"Explore this angle: {q}" for q in selected]

    # Storyteller or other: narrative, metaphor-driven
    selected = pool[:count]
    return [f"Imagine this: {q}" for q in selected]


# ── Error diagnosis ───────────────────────────────────────────────────────────

_CORRECTION_TEMPLATES: dict[str, str] = {
    "socratic": (
        "I notice you ran into a challenge with {error}. That's actually a great learning moment. "
        "Let's think about what might have caused that. What did you expect to happen, and what actually happened? "
        "Often the gap between expectation and reality is where the real learning lives. "
        "Take a moment to trace through your logic—what assumption might have led you astray?"
    ),
    "direct": (
        "Error detected: {error}. Here's the fix—{correction}. "
        "You need to understand why that was wrong. The correct approach is {correct_approach}. "
        "Now repeat it until you get it right. No shortcuts."
    ),
    "inquiry": (
        "Interesting—you encountered {error}. Let's unpack that together. "
        "What was your thinking when you wrote that code? There's usually a reasonable intuition behind a mistake. "
        "Let's look at what the code actually did versus what you intended. "
        "I'd suggest checking {resource} for a deeper dive into this area."
    ),
    "narrative": (
        "Ah, {error}—a twist in our story! Even the greatest programmers have stumbled here. "
        "Let me tell you about a time when a similar mistake taught someone an invaluable lesson. "
        "The lesson? {lesson}. So next time, remember: {wisdom}."
    ),
}


def diagnose_errors(teacher: TeacherProfile, errors: list[str]) -> str:
    """Analyze learner errors and produce corrective feedback in the teacher's voice.

    Args:
        teacher: The teacher whose voice and correction style to use.
        errors: A list of error descriptions from the learner's recent work.

    Returns:
        Corrective feedback string in the teacher's distinctive voice.
    """
    if not errors:
        return (
            "No errors to address—excellent work! Keep up this focused approach. "
            "If anything feels uncertain, remember that asking questions is a sign of engagement, not weakness."
        )

    # Use the first error as the primary focus, acknowledge others briefly
    primary_error = errors[0]
    extra_errors = errors[1:]

    template = _CORRECTION_TEMPLATES.get(
        teacher.teaching_style,
        _CORRECTION_TEMPLATES["socratic"],
    )

    if teacher.teaching_style == "narrative":
        # Storyteller uses analogies
        lesson = {
            "socratic": "the value of pausing to question your assumptions before acting.",
            "direct": "precision matters—every character counts.",
            "inquiry": "understanding the 'why' behind an error prevents it from recurring.",
            "narrative": "even mistakes are chapters in the larger story of mastery.",
        }.get(teacher.teaching_style, "every challenge is a chance to grow.")

        wisdom = {
            "socratic": "the answer is often hidden in the question you haven't asked yet.",
            "direct": "slow is smooth, and smooth is fast.",
            "inquiry": "the best resource is the one you haven't discovered yet.",
            "narrative": "every great story has a turning point—this is yours.",
        }.get(teacher.teaching_style, "keep going.")

        return template.format(
            error=primary_error,
            lesson=lesson,
            wisdom=wisdom,
        )

    # For other styles, provide corrective guidance
    correction = _suggest_correction(primary_error)
    correct_approach = _suggest_correction(primary_error, focus_on_approach=True)
    resource = _suggest_resource(primary_error)

    result = template.format(
        error=primary_error,
        correction=correction,
        correct_approach=correct_approach,
        resource=resource,
    )

    if extra_errors:
        let_s_redirect = (
            "Let's tackle these one at a time."
            if teacher.patience_level in ("high", "medium")
            else "Address these now."
        )
        result += f"\n\nI also noticed: {'; '.join(extra_errors)}. {let_s_redirect}"

    return result


def _suggest_correction(error: str, focus_on_approach: bool = False) -> str:
    """Generate a plausible correction suggestion based on the error text."""
    error_lower = error.lower()
    if "variable" in error_lower or "undefined" in error_lower:
        return (
            "the variable needs to be declared before use."
            if focus_on_approach
            else "Declare the variable before referencing it."
        )
    if "function" in error_lower or "call" in error_lower:
        return (
            "check the function signature and argument order."
            if focus_on_approach
            else "Verify the function name, parameters, and return handling."
        )
    if "loop" in error_lower or "infinite" in error_lower:
        return (
            "the loop condition must eventually become false."
            if focus_on_approach
            else "Add a proper termination condition to the loop."
        )
    if "index" in error_lower or "out of range" in error_lower:
        return (
            "array indices start at 0 and end at length-1."
            if focus_on_approach
            else "Check that your index is within the valid range [0, length)."
        )
    if "type" in error_lower or "casting" in error_lower:
        return (
            "ensure operands are of compatible types."
            if focus_on_approach
            else "Convert values to compatible types before operating on them."
        )
    return "review the relevant concept and double-check your logic."


def _suggest_resource(error: str) -> str:
    """Suggest a resource topic based on the error."""
    error_lower = error.lower()
    if "variable" in error_lower:
        return "the variables and scope section in your course materials"
    if "function" in error_lower:
        return "the functions and parameters reference"
    if "loop" in error_lower:
        return "the control flow and loops chapter"
    if "index" in error_lower:
        return "the arrays and indexing guide"
    if "type" in error_lower:
        return "the type system and type conversion docs"
    return "the relevant section in your learning materials"


# ── TTS voice mapping ────────────────────────────────────────────────────────

_VOICE_MAP: dict[str, str] = {
    "alloy": "alloy",
    "shimmer": "shimmer",
    "nova": "nova",
    "fable": "fable",
    "echo": "echo",
    "onyx": "onyx",
}


def get_tts_voice(teacher: TeacherProfile) -> str:
    """Map a teacher's voice preference to an actual TTS voice identifier.

    Args:
        teacher: The teacher whose voice to resolve.

    Returns:
        A TTS voice identifier string suitable for speech synthesis.
    """
    preferred = teacher.voice.lower().strip()
    return _VOICE_MAP.get(preferred, "alloy")


# ── Main instruction entry point ─────────────────────────────────────────────


def instruct(
    teacher_name: str, topic: str, learner_state: LearnerState | None = None
) -> LessonContent:
    """Generate personality-tailored lesson content for a teacher and topic.

    Uses the teacher's profile to shape the greeting, explanation style,
    questions, practice exercises, and encouragement. If learner_state is
    provided and contains errors, corrective guidance is woven into the output.

    Args:
        teacher_name: Name of the teacher (case-insensitive).
        topic: The topic to generate instruction for.
        learner_state: Optional learner state; errors trigger corrective feedback.

    Returns:
        A LessonContent instance with all fields populated.
    """
    teacher = get_teacher(teacher_name)
    base = _generate_content(teacher, topic, learner_state)

    # Generate Socratic questions
    questions = generate_socratic_questions(teacher, topic)

    # Incorporate error diagnosis if applicable
    if learner_state and learner_state.errors:
        correction = diagnose_errors(teacher, learner_state.errors)
        # Prepend correction to the explanation for direct teachers,
        # append for others
        if teacher.teaching_style == "direct":
            base["explanation"] = f"{correction}\n\n{base['explanation']}"
        else:
            base["explanation"] = f"{base['explanation']}\n\n{correction}"

    # Build the lesson content
    return LessonContent(
        teacher_name=teacher.name,
        topic=topic,
        greeting=teacher.greeting,
        explanation=base["explanation"],
        example=base["example"],
        questions=questions,
        practice_exercises=base["practice_exercises"],
        encouragement=base["encouragement"],
        tts_voice=get_tts_voice(teacher),
    )
